### ISSUE TITLE
Agricultural Exposure service broken

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/natmap-catalog-v8#26]
Should this link be removed or updated?

![image](https://user-images.githubusercontent.com/41275384/129671488-d5813b86-2a29-49fc-847b-98044ca3c11e.png)

**Comment by AnaBelgun** [comment]
The service http://services.ga.gov.au/site_9/rest/services/NEXIS_Agricultural_Exposure/MapServer is no longer available 
Please let's remove it from the catalogue

**Comment by AnaBelgun** [comment]
Removed from catalogue in https://nationalmap-2021-09-03.nm.terria.io/
