### ISSUE TITLE
Need instructions on how to update catalogs

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/natmap-catalog-v8#8]
This is particularly important during the transition from v7 to v8.

**Comment by tephenavies** [comment]
Information is in a readme in https://github.com/TerriaJS/natmap-catalog-v8. We should link to this from https://github.com/TerriaJS/handbook (as mentioned all release manager content should be linked from the handbook).

**Comment by tephenavies** [comment]
Closed. Nick will continue with GitHub catalog management for v8 saas + nationalmap
